# Generated by Django 5.2.8 on 2025-11-29 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laundryapp", "0002_customer_staff_alter_address_mobile_no_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="mobile_no",
        ),
        migrations.RemoveField(
            model_name="address",
            name="name",
        ),
    ]
