# Generated by Django 5.2.8 on 2025-11-29 09:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundryapp", "0003_remove_address_mobile_no_remove_address_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="address",
            name="object_id",
        ),
        migrations.AddField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                default="1",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
            ),
            preserve_default=False,
        ),
    ]
