# Generated by Django 5.2.8 on 2025-11-29 10:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundryapp", "0006_alter_address_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="otp_code",
        ),
        migrations.RemoveField(
            model_name="user",
            name="otp_created_at",
        ),
        migrations.RemoveField(
            model_name="user",
            name="otp_expires_at",
        ),
        migrations.AlterField(
            model_name="address",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="addresses",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="customer",
            name="mobile_no",
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
