# Generated by Django 5.2.8 on 2025-12-02 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundryapp", "0008_user_otp_code_user_otp_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
