# Generated by Django 5.2.8 on 2025-12-03 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundryapp", "0009_order_confirmed_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("customer", "Customer"),
                    ("staff", "Staff"),
                    ("admin", "Admin"),
                ],
                default="admin",
                max_length=20,
            ),
        ),
    ]
