# Generated by Django 5.2.8 on 2025-12-04 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundryapp", "0010_alter_user_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
    ]
