# Generated by Django 5.2.8 on 2025-12-05 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundryapp", "0012_alter_order_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="caddress_type",
            field=models.CharField(
                choices=[("home", "Home"), ("work", "Work"), ("other", "Other")],
                default="home",
                help_text="Specify whether the address is home, work, or other",
                max_length=10,
            ),
        ),
    ]
