# Generated by Django 5.2.8 on 2025-12-05 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laundryapp", "0013_address_caddress_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="caddress_type",
            new_name="address_type",
        ),
    ]
