# Generated by Django 5.2.8 on 2025-12-06 06:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("laundryapp", "0014_rename_caddress_type_address_address_type"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Staff",
        ),
    ]
