# Generated by Django 5.2.8 on 2025-12-06 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundryapp", "0015_delete_staff"),
    ]

    operations = [
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, unique=True
                    ),
                ),
                ("mobile_no", models.CharField(blank=True, max_length=20, null=True)),
                ("role", models.CharField(default="Staff", max_length=20)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("inactive", "Inactive"),
                            ("blocked", "Blocked"),
                        ],
                        default="active",
                        max_length=20,
                    ),
                ),
                ("image_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_staff", models.BooleanField(default=False)),
            ],
        ),
    ]
