# Generated by Django 5.2.8 on 2025-12-10 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundryapp", "0016_staff"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("pending", "Pending"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
