# Generated by Django 5.2.9 on 2025-12-17 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundryapp", "0017_alter_customer_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="is_primary",
            field=models.BooleanField(
                default=False, help_text="Mark this address as primary"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="Token_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
