# Generated by Django 5.2.9 on 2026-01-13 09:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("laundryapp", "0018_address_is_primary_alter_order_token_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), editable=False, max_digits=12
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="price",
            field=models.DecimalField(
                decimal_places=2, default="0", editable=False, max_digits=10
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="orderitem",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default="0", editable=False, max_digits=12
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(default="pending", max_length=50),
        ),
    ]
